### ISSUE TITLE
toggle() type signature does not match implementation

### ISSUE THREAD

**Issue by feliskio** [yoannfleurydev/react-use-disclosure#430]
The type signature of `toggle` does not define any arguments.
As a result from the outside it looks like it is safe to use directly as event handler, which is not the case.
Even worse using `toggle` directly as event handler sets `isOpen` to a non-boolean value.

Therefore I suggest the following changes:

1. Adjust the type signature of `toggle` to include `toSet`
2. Cast the value of `toSet` to boolean

I'd happily open PRs for both of these.

**Comment by yoannfleurydev** [comment]
Hi, you are right, changes have been made to code without impacting them to the TS definition. 

I agree with your changes, feel free to submit PRs, I'll review and release them as soon as possible.
Thanks a lot for opening this issue.
